version: '3.7'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - mysql-app
    env_file:
      - ./.env
    volumes:
      # - ./:/usr/src/app  로컬 환경에서, 파일의 변경사항이 바로바로 적용되도록 주석처리
      - /usr/src/app/node_modules
  mysql-app:
    platform: linux/x86_64    # mac m1
    container_name: local-db  # 나중에 db host 로 사ㅇ
    restart: always
    image: mysql:latest
    env_file:
      - ./.env
    ports:
      - 3306:3306
    networks:
      - my-network
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
networks:
  my-network:
